<?php
/**
 * Implements hook_menu().
 */
function egbolig_menu() {
  $items['admin/config/system/egbolig'] = array(
    'title'            => t('Configure EGbolig'),
    'description'      => t('Configure EGbolig settings'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('egbolig_settings'),
    'access arguments' => array('access administration pages'),
    'type'             => MENU_NORMAL_ITEM,
  );

  return $items;
}

function egbolig_settings() {
  $form = array();

  $form['soap_webservice'] = array(
    '#type' => 'textfield',
    '#title' => 'Webservice URL',
    '#required' => TRUE,
    '#default_value' => variable_get('soap_webservice', NULL),
    '#description' => 'http://egboligws.ballerup.dk/services/service10632.svc?wsdl',
  );

  return system_settings_form($form);
}


/**
 * Webform options info callback.
 */
function education_get_list() {
  $client = new SoapClient(variable_get('soap_webservice'));
  $educations = $client->EducationGetList()->EducationGetListResult->Education;
  $edulist = array();

  foreach ($educations as $education) {
    if (strlen($education->Name) == 1) {
      continue;
    }
    elseif ($education->Name == 'æ' || $education->Name == 'ø' || $education->Name == 'å') {
      continue;
    }
    else {
      $edulist[] = _upper_case($education->Name);
    }
  }

  return $edulist;
}

function education_places() {
  $placeslist = array();
  $client = new SoapClient(variable_get('soap_webservice'));
  $education_places =  
    $client->EducationalInstitutionGetList()->
    EducationalInstitutionGetListResult->
    EducationalInstitution;
  if(count($education_places) > 0) {
    foreach($education_places as $place)
    {
        $placeslist[] = $place->Name;
    }
  }
  else {
    $placeslist[] = 'Ingen uddannelsessteder';
  }
  return $placeslist;
}

function accomodation_types() {
  $accomodationlist = array();
  $client = new SoapClient(variable_get('soap_webservice'));
  $apartment_types =
    $client->TenancyTypeGetList()->
    TenancyTypeGetListResult->
    TenancyType;
  foreach($apartment_types as $type) {
      $accomodationlist[] = $type->Text;
  }
  return $accomodationlist;
}


function _upper_case($string) {
  $first_letter = substr($string, 0, 2);
  switch($first_letter) {
  case 'æ':
    return 'Æ'.substr($string, 2);
    break;
  case 'ø':
    return 'Ø'.substr($string, 2);
    break;
  case 'å':
    return 'Å'.substr($string, 2);
    break;
  default:
    return ucfirst($string);
  }
}
